import argparse
import platform
import subprocess
import tomllib
from pathlib import Path


ROOT = Path(__file__).parent
IS_WINDOWS = platform.system() == "Windows"
BINARY_NAME = "treesnake.exe" if IS_WINDOWS else "treesnake"


def read_version() -> str:
    with open(ROOT / "pyproject.toml", "rb") as f:
        return tomllib.load(f)["project"]["version"]


def write_version_file(version: str) -> None:
    version_file = ROOT / "cli" / "_version.py"
    version_file.write_text(
        f'# auto-generated by build.py, do not edit\n__version__ = "{version}"\n'
    )
    print(f"[build] version: {version}")


def write_spec_file() -> None:
    spec = ROOT / "treesnake.spec"
    spec.write_text(
        """\
# -*- mode: python ; coding: utf-8 -*-
import platform

IS_WINDOWS = platform.system() == "Windows"

a = Analysis(
    ['src/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='treesnake',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=IS_WINDOWS,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
""",
        encoding="utf-8",
    )
    print("[build] treesnake.spec generated")


def run(cmd: list[str]) -> None:
    print(f"[build] running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--version-only",
        action="store_true",
        help="Only generate cli/_version.py, skip build",
    )
    args = parser.parse_args()

    version = read_version()
    write_version_file(version)

    if args.version_only:
        print("[build] version file written, skipping build")
        return

    write_spec_file()
    run(["pyinstaller", "treesnake.spec"])
    print(f"[build] done → dist/{BINARY_NAME}")


if __name__ == "__main__":
    main()